# fly.toml file generated for apoor-ssh on 2023-03-04T19:17:06-08:00

app = "apoor-ssh"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.env]
  name = "BP_GO_TARGETS" 
  value = "./cmd/server"

[env]
  APP_HOST="0.0.0.0"
  APP_PORT="23234"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 23234
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 22

  # [[services.tcp_checks]]
  #   grace_period = "1s"
  #   interval = "15s"
  #   restart_limit = 0
  #   timeout = "2s"
